# Generated by Django 5.2.11 on 2026-06-10 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0002_registration_alter_contact_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registration',
            options={'verbose_name': 'Регистрация', 'verbose_name_plural': 'Регистрации'},
        ),
        migrations.RenameField(
            model_name='registration',
            old_name='emai',
            new_name='email',
        ),
    ]
