# Generated by Django 5.2.11 on 2026-07-25 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0005_registration_created_at_registration_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название тарифа')),
                ('subjects_count', models.PositiveSmallIntegerField(verbose_name='Количество предметов')),
                ('lessons_per_month', models.PositiveSmallIntegerField(verbose_name='Занятий в месяц')),
            ],
            options={
                'verbose_name': 'Тариф',
                'verbose_name_plural': 'Тарифы',
            },
        ),
        migrations.AddField(
            model_name='registration',
            name='grade',
            field=models.CharField(blank=True, max_length=20, verbose_name='Класс'),
        ),
        migrations.AddField(
            model_name='registration',
            name='subscription_until',
            field=models.DateField(blank=True, null=True, verbose_name='Действует до'),
        ),
        migrations.AddField(
            model_name='registration',
            name='tariff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_page.tariff', verbose_name='Тариф'),
        ),
    ]
