# Generated by Django 5.2.11 on 2026-08-03 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0008_alter_registration_phone_homework'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='teacher_file',
            field=models.FileField(blank=True, null=True, upload_to='homework/student/%Y/%m/', verbose_name='Файл учителя'),
        ),
    ]
