# Generated by Django 5.2.11 on 2026-06-14 04:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0004_alter_registration_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата заявки'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registration',
            name='status',
            field=models.CharField(choices=[('new', 'Новая заявка'), ('contacted', 'Связались с клиентом'), ('approved', 'Одобрена, аккаунт создан'), ('rejected', 'Отклонена')], default='new', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='password',
            field=models.CharField(max_length=255, verbose_name='Пароль'),
        ),
    ]
