# Generated by Django 5.2.11 on 2026-07-29 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0006_tariff_registration_grade_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True, verbose_name='Предмет')),
            ],
            options={
                'verbose_name': 'Предмет',
                'verbose_name_plural': 'Предметы',
            },
        ),
        migrations.RemoveField(
            model_name='tariff',
            name='subjects_count',
        ),
        migrations.AddField(
            model_name='tariff',
            name='subjects_of_study',
            field=models.ManyToManyField(to='main_page.subject', verbose_name='Предметы'),
        ),
    ]
